import type { Metadata } from 'next';
import './globals.css';
import { Montserrat } from 'next/font/google';

export const metadata: Metadata = {
  title: 'Campus Innovate',
  description: 'Generated by Campus Innovate',
  authors: [{name: "Zidane Ibrahim Fadela"}],
  icons: {
    icon: '/assets/logos/logo-campus-innovate.png'
  },
  openGraph: {
    type: 'website',
    title: 'Campus Innovate',
    
  }
};

const montserrat = Montserrat({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={montserrat.className}
      >
        {children}
      </body>
    </html>
  );
}
